
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xebB\x9b,\x1a\x89\xaa,wV\x12\x96\xcd\xa25\x99'
    
_lr_action_items = {'AND':([3,6,7,8,11,14,15,16,17,],[-9,13,-6,-4,-5,13,-8,-7,-3,]),'TERMS':([0,2,4,5,9,13,],[3,10,3,3,3,3,]),'QUOTES':([0,4,5,9,10,13,],[2,2,2,2,15,2,]),'LPAREN':([0,4,5,9,13,],[5,5,5,5,5,]),'NOT':([0,4,5,9,13,],[4,4,4,4,4,]),'RPAREN':([3,6,7,8,11,12,14,15,16,17,],[-9,-2,-6,-4,-5,16,-1,-8,-7,-3,]),'OR':([1,3,6,7,8,11,12,14,15,16,17,],[9,-9,-2,-6,-4,9,9,-1,-8,-7,-3,]),'$end':([1,3,6,7,8,11,14,15,16,17,],[0,-9,-2,-6,-4,-5,-1,-8,-7,-3,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression1':([0,4,5,9,],[6,6,6,14,]),'query':([0,4,5,9,13,],[7,7,7,7,7,]),'expression':([0,4,5,9,13,],[8,8,8,8,17,]),'start_expression':([0,4,5,],[1,11,12,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start_expression","S'",1,None,None,None),
  ('start_expression -> start_expression OR expression1','start_expression',3,'p_expression_or','/home/arsenal/Information-Retrieval/Information-Retrieval/InvertedIndex/parser.py',14),
  ('start_expression -> expression1','start_expression',1,'p_expression_or','/home/arsenal/Information-Retrieval/Information-Retrieval/InvertedIndex/parser.py',15),
  ('expression1 -> expression1 AND expression','expression1',3,'p_expression_and','/home/arsenal/Information-Retrieval/Information-Retrieval/InvertedIndex/parser.py',31),
  ('expression1 -> expression','expression1',1,'p_expression_and','/home/arsenal/Information-Retrieval/Information-Retrieval/InvertedIndex/parser.py',32),
  ('expression -> NOT start_expression','expression',2,'p_expression_not','/home/arsenal/Information-Retrieval/Information-Retrieval/InvertedIndex/parser.py',46),
  ('expression -> query','expression',1,'p_expression_not','/home/arsenal/Information-Retrieval/Information-Retrieval/InvertedIndex/parser.py',47),
  ('expression -> LPAREN start_expression RPAREN','expression',3,'p_expression_not','/home/arsenal/Information-Retrieval/Information-Retrieval/InvertedIndex/parser.py',48),
  ('query -> QUOTES TERMS QUOTES','query',3,'p_expression_query','/home/arsenal/Information-Retrieval/Information-Retrieval/InvertedIndex/parser.py',66),
  ('query -> TERMS','query',1,'p_expression_query','/home/arsenal/Information-Retrieval/Information-Retrieval/InvertedIndex/parser.py',67),
]
